### ISSUE TITLE
Low and high pass filters to smooth out edges of cutoff points

### ISSUE THREAD

**Issue by JonasBjordal** [phandasm/waveform#12]
The edges of the spectrum end abruptly at the cutoff points set in the settings if the audio source has a wider span in frequencies. I'd like to highlight a specific part of the spectrum, but to avoid the rough edges I have to maximize the cutoff points and/or increase the floor value at the moment.
A slider to control a roll-off from these points would be really practical to smooth out the waveform on the sides, just like low pass or high pass filters with frequency and Q/bandwith values just like in EQs you'd find in DAWs.

**Comment by phandasm** [comment]
That's not a bad idea.
I worry about cramming an ever increasing number controls into an already crowded settings panel though, so I think I would do this as just 2 sliders for bandwidth and roll-off rate affecting both cutoff points equally

**Comment by phandasm** [comment]
Added as of 1.4.0
