### ISSUE TITLE
Works on Arm64 Mac

### ISSUE THREAD

**Issue by froxcey** [phandasm/waveform#13]
I have an arm Mac, and I tested the OBS plugin. On the release page, it says it's x64 only, but it works perfectly fine on my machine. It's smooth, and everything works.

![Screenshot 2022-05-20 at 12 08 20 PM (2)](https://user-images.githubusercontent.com/51555391/169448664-fc388cb5-90af-472c-9adf-46391765d261.png)

**Comment by phandasm** [comment]
The M1 macs have emulation for running x86 software on ARM CPUs (google M1 rosetta 2).
This is almost guaranteed to impact performance and Apple may eventually drop support for rosetta (or make it optional) so I don't want to claim to support ARM until a native build is available.

**Comment by kilinbox** [comment]
I was able to build arm64 with the following command. 

> cmake -DLibObs_ROOT="../obs-studio" -DDISABLE_X86_SIMD=ON -DBUILTIN_FFTW=ON -DCMAKE_OSX_ARCHITECTURES=arm64 -B build .
> cmake --build build --config Release

Thanks
![Screen-Shot](https://user-images.githubusercontent.com/17141779/170250167-4a511cfc-f354-4d34-9d13-cf733a879359.jpg)
.

**Comment by phandasm** [comment]
Native ARM builds now provided as of 1.4.0
