### ISSUE TITLE
A simplified Chinese translation file

### ISSUE THREAD

**Issue by GodGun968** [phandasm/waveform#14]
You have produced a very good document
There are now more Chinese people using
But this file is not Chinese
So I created a simplified Chinese translation file
I hope you can add it to your project(This directory:data\obs-plugins\waveform\locale)
Add it when releasing a new version
Thank you
Remember to decompress:(or this linkhttps://raw.githubusercontent.com/GodGun968/test/main/zh-CN.ini But please make sure it is UTF-8 encoded)
[zh-CN.zip](https://github.com/phandasm/waveform/files/8738557/zh-CN.zip)

**Comment by GodGun968** [comment]
My English is not particularly good, so please forgive me if what I say offends you.

**Comment by phandasm** [comment]
Thank you!
I'll be sure to include that for the next release.
