### ISSUE TITLE
Option to remove sound floor graph line entirely

### ISSUE THREAD

**Issue by JonasBjordal** [phandasm/waveform#15]
I like the toggle option to hide the graph when the audio is silent, but if it removed the floor line entirely it'd be looking a lot better in my opinion. The line sticks out quite a bit when the visualizer has an exposed line for the sound floor or when using the stereo channel spacing feature recently added, in which the second channel will have no line at all (which looks a lot nicer).

Basically what I'm asking for is an update where neither channel has the horizontal sound floor line when the "hide graph when silent" toggle is selected for the curve and bar display modes,

**Comment by JonasBjordal** [comment]
I mean the latter, and hiding the line that's showing the sound floor would probably be a perfect solution, yeah! 
I just thought it had a simple solution at first as the second stereo channel doesn't have the line at all if it's separated from the other when using the curve mode

**Comment by phandasm** [comment]
So this seems to have been somewhat incidentally solved as I was cleaning up the rendering code.
In my testing I no longer see the floor line but I also didn't see it in most cases to begin with so I'm not 100% sure it's gone.
If you still see it let me know and I'll reopen the issue.
