### ISSUE TITLE
Plugin does not work after restarting OBS

### ISSUE THREAD

**Issue by kochetov2000** [phandasm/waveform#2]
After restarting OBS with the "Auto FFT size" and "Fast Peaks" settings turned off, the plugin does not display anything and starts working again when switching any settings.

**Comment by phandasm** [comment]
That sounds like maybe it failed to capture the audio during initial bootup?
I've added more logging to help diagnose things like this in the future.
In the meantime if you happen to know your CPU or can post the bit at the top of your log file that looks like this:
```
[waveform]: Registered v1.0.0 64-bit
[waveform]: Using CPU capabilities: AVX2 AVX SSE4.1 FMA3 SSE2
```
It would help narrow down the search.

**Comment by kochetov2000** [comment]
My CPU Intel® Core™ i3-9100F

**Comment by kochetov2000** [comment]
I figured out what the reason is - I am using another audio device for music to separate audio tracks. Initially I added a second audio device to the stage as an audio source, but then I decided to try to select the desktop device 2 in the settings of the obs itself, and after that the plug-in began to capture sound normally. Apparently, when starting the obs, the audio source added to the scene is initialized later, which is why the plug-in refused to accept its sound

**Comment by phandasm** [comment]
Ah, that would make sense.
I'll have to have it retry the capture periodically.
