### ISSUE TITLE
OBS-studio native ARM build not finding the plugin (also ARM native)

### ISSUE THREAD

**Issue by thmsdj** [phandasm/waveform#20]
Hello,

When I try to start the plugin (native ARM), it cannot be found in the OBS sources. I have tried the latest nightly build: 27.2.0-521-g889ca0fc0 and also the version 27.2.0-118-g3b7d42757. 

When trying to use the X64 version of OBS and also your plugin, the plugin prompts for security approval (which means that it can use the plugin). After this the plugin can be found in OBS sources, as usual. 

Machine: Macbook Air M1 16gb / 512gb. Big Sur 11.6.6. (I know it might be the time to upgrade to Monterey, lol)

Thanks for looking into this, and if you need any more information - let me know!

**Comment by phandasm** [comment]
Bizarre.
Does the log file say anything?
In particular it might say something like `Skipping module '[filename]', not an OBS plugin` or `Failed to initialize module '[filename]'`

I'll have to look into it but sadly I don't have an M1 to test with so I have no idea what the issue could be. Maybe it expects ARM binaries to be in a different folder, like `32bit` vs `64bit` on windows?

**Comment by thmsdj** [comment]
@phandasm In the logfile after a successful load on 64bit Intel (not ARM):

11:27:17.693: Failed to load 'en-GB' text for module: 'libwaveform.so'
11:27:17.693: [phandasm_waveform]: Registered v1.3.0 64-bit
11:27:17.693: [phandasm_waveform]: Using CPU capabilities: SSE2
11:27:17.693: ---------------------------------
11:27:17.693:   Loaded Modules:
11:27:17.693:     libwaveform.so

Unfortunately the ARM version is not loading at all. It is even not prompting with the security message. Very bizarre indeed, it seems that it is not loading the module at all when using an ARM version of OBS and your plugin. 

Thanks for the help!

**Comment by kilinbox** [comment]
@thmsdj
Hello, 
How about rename libwaveform.so to waveform.so ?

before:
/Library/Application Support/obs-studio/plugins/waveform/bin/libwaveform.so

after:
/Library/Application Support/obs-studio/plugins/waveform/bin/waveform.so

**Comment by kilinbox** [comment]
@thmsdj

I installed waveform(arm64) on "obs-27.2.0-521-g889ca0fc0(arm64)
https://github.com/obsproject/obs-studio/actions/runs/2531858020

![obs-waveform](https://user-images.githubusercontent.com/17141779/175284205-888ce801-c77b-46ab-b5ef-e8f23609f2b6.png)

**Comment by thmsdj** [comment]
Where to get that build of OBS ARM @kilinbox

**Comment by phandasm** [comment]
Glad you got it working!
Is it actually necessary to rename it to just 'waveform.so' though?
The 'lib' prefix wasn't an issue on other platforms so I just left it but I guess that may have been a mistake.

**Comment by thmsdj** [comment]
@phandasm Can't tell. Tried a small name change and it seems that at least in a loaded instance it will only find waveform.so but not libwaveform.so. Weird. Anyways, thanks for the help - did a test yesterday (I am a twitch streamer) and it worked perfectly.

**Comment by phandasm** [comment]
Good to know, guess I'll remove the prefix just to be safe.
Since everything seems to be sorted out now, I'll go ahead and close this.
