### ISSUE TITLE
OBS crashes under Ubuntu 20.04

### ISSUE THREAD

**Issue by salarelv** [phandasm/waveform#21]
When I install the plugin from Flatpak or directly copy the plugin to plugins folder OBS crashes when launching.

error: os_dlopen(libnvidia-encode.so.1->libnvidia-encode.so.1): libnvidia-encode.so.1: cannot open shared object file: No such file or directory

OBS version 27.2.4

When I installed libnvidia-encode-510-server then this error dissappeared but now it returns "Illegal instruction"

NB! System doesnt have a NVIDIA GPU.

Attempted path: share/obs/obs-studio/locale/en-US.ini
Attempted path: /usr/share/obs/obs-studio/locale/en-US.ini
Attempted path: share/obs/obs-studio/locale.ini
Attempted path: /usr/share/obs/obs-studio/locale.ini
Attempted path: share/obs/obs-studio/locale/en-GB.ini
Attempted path: /usr/share/obs/obs-studio/locale/en-GB.ini
info: Using preferred locale 'en-GB'
Attempted path: share/obs/obs-studio/themes/Dark.qss
Attempted path: /usr/share/obs/obs-studio/themes/Dark.qss
info: CPU Name: Intel(R) Pentium(R) Silver J5040 CPU @ 2.00GHz
info: CPU Speed: 2993.953MHz
info: Physical Cores: 4, Logical Cores: 4
info: Physical Memory: 7535MB Total, 2089MB Free
info: Kernel Version: Linux 5.13.0-51-generic
info: Distribution: "KDE neon" "20.04"
info: Session Type: x11
info: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.20.13
info: Qt Version: 5.15.4 (runtime), 5.12.8 (compiled)
info: Portable mode: false
Attempted path: share/obs/obs-studio/themes/Dark/no_sources.svg
Attempted path: /usr/share/obs/obs-studio/themes/Dark/no_sources.svg
QMetaObject::connectSlotsByName: No matching signal for on_tbar_position_valueChanged(int)
QMetaObject::connectSlotsByName: No matching signal for on_actionShowTransitionProperties_triggered()
QMetaObject::connectSlotsByName: No matching signal for on_actionHideTransitionProperties_triggered()
info: OBS 27.2.4 (linux)
info: ---------------------------------
info: ---------------------------------
info: audio settings reset:
        samples per sec: 48000
        speakers:        2
info: ---------------------------------
info: Initializing OpenGL...
info: Loading up OpenGL on adapter Intel Mesa Intel(R) UHD Graphics 605 (GLK 3)
info: OpenGL loaded successfully, version 4.6 (Core Profile) Mesa 21.2.6, shading language 4.60
info: ---------------------------------
info: video settings reset:
        base resolution:   1920x1080
        output resolution: 1280x720
        downscale filter:  Bicubic
        fps:               30/1
        format:            NV12
        YUV mode:          709/Partial
info: NV12 texture support not available
info: Audio monitoring device:
        name: Default
        id: default
info: ---------------------------------
warning: Failed to load 'en-GB' text for module: 'aja-output-ui.so'
warning: No AJA devices found, skipping loading AJA UI plugin
warning: Failed to initialize module 'aja-output-ui.so'
warning: Failed to load 'en-GB' text for module: 'aja.so'
warning: No AJA devices found, skipping loading AJA plugin
warning: Failed to initialize module 'aja.so'
warning: Failed to load 'en-US' text for module: 'decklink-captions.so'
warning: Failed to load 'en-US' text for module: 'decklink-ouput-ui.so'
warning: Failed to load 'en-GB' text for module: 'frontend-tools.so'
warning: Failed to load 'en-GB' text for module: 'linux-alsa.so'
warning: Failed to load 'en-GB' text for module: 'linux-capture.so'
libDeckLinkAPI.so: cannot open shared object file: No such file or directory
warning: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
info: No blackmagic support
warning: Failed to load 'en-GB' text for module: 'linux-jack.so'
warning: Failed to load 'en-GB' text for module: 'linux-pulseaudio.so'
warning: v4l2loopback not installed, virtual camera disabled
info: [obs-browser]: Version 2.17.13
info: [obs-browser]: CEF Version 95.0.0-MediaHandler.2463+g3b3ac84+chromium-95.0.4638.69
info: NVENC supported
info: FFMPEG VAAPI supported
warning: Failed to load 'en-GB' text for module: 'obs-libfdk.so'
warning: Failed to load 'en-GB' text for module: 'obs-vst.so'
warning: Failed to load 'en-GB' text for module: 'obs-x264.so'
warning: Failed to load 'en-GB' text for module: 'rtmp-services.so'
info: [vlc-video]: VLC 3.0.9.2 Vetinari found, VLC video source enabled
Illegal instruction

**Comment by phandasm** [comment]
The nvidia thing is definitely not required, I get that message too.
I tested both the binary from the release page and the flatpak build on an AMD system running Ubuntu 20.04, shouldn't be any dependency on anything nvidia.

Does your CPU support AVX? That'd be my guess as to the illegal instruction error.
as of v1.4 waveform requires AVX support, 1.3 does not so if that one works then that's probably why.

**Comment by salarelv** [comment]
It crashed on a Intel J5040. Seems that this 2019 CPU doesnt have AVX (at least on Wikipedia doesnt mention this family of CPUs? On a 7700HQ it works fine. 
Maybe would be nice to make it so it wouldn't crash OBS.

**Comment by salarelv** [comment]
Bummer. It was cheap and low TDP. Create to use in flight case.

**Comment by phandasm** [comment]
Restored non-AVX support in 1.4.1
