### ISSUE TITLE
plugin conflict with <obs-color-monitor>

### ISSUE THREAD

**Issue by kirahan** [phandasm/waveform#3]
WaveForm is a very cool plugin, but it seems conflict with <obs-color-monitor>, cause both source_name warmform is been used in this 2 plugins. Hope there is some way to use this 2 plugin at the same time

<obs-color-monitor> 
 [obs forum page](https://obsproject.com/forum/resources/obs-color-monitor.1277/)
 [github page](https://github.com/norihiro/obs-color-monitor)

**Comment by phandasm** [comment]
This is already fixed in the current source build.
Next release should be soon(ish) if you can't build it yourself.
