### ISSUE TITLE
macos installer doesnt work

### ISSUE THREAD

**Issue by dravpin** [phandasm/waveform#35]
the installer makes it through to the end but when you open obs you can add wavefore

**Comment by phandasm** [comment]
Are you sure you got the right architecture to match your OBS (e.g. x86 waveform with x86 OBS, or ARM waveform with ARM OBS)?

Also, someone else reported this but got it to work by reinstalling OBS: https://github.com/phandasm/waveform/issues/31#issuecomment-1327219344
Not sure what to make of that, but to my knowledge the installer *should* work.

**Comment by cmsj** [comment]
I just ran into something similar - I think it might be that OBS isn't looking in `/Library/Application Support/obs-studio/plugins/` anymore. I moved `waveform.plugin` to `~/Library/Application Support/obs-studio/plugins/` and now I can add it as a source.

**Comment by phandasm** [comment]
Oops, apparently I forgot to fix that for x64.
Thanks.
