### ISSUE TITLE
[Linux-28.1.2][v1.6.0-beta3] Weird pattern in radial bars

### ISSUE THREAD

**Issue by Commaster** [phandasm/waveform#36]
![image](https://user-images.githubusercontent.com/1367092/209836253-9c945247-af93-4e7e-b65e-09c984da9a79.png)

Using the following settings (most of while don't really matter, I think):
```
Normalize Volume
Bars 1-1-0 (You could say it's basically the Curve mode)
700x700
Logarithmic Frequency Scale
Radial-Inverted
20% deadzone
90% Radial Arc
Rounded Caps
Auto FFT Size
Hann - None - Lanczos - None
30-17500 Hz
-65 - 0 dBFS
```

Of course setting the mode to Curve removes the patterns...

**Comment by phandasm** [comment]
Yeah, if you use bars that small it's going to artifact.
There's not much that can reasonably be done about it since it's a product of floating point error and aliasing from trying to render primitives with sub-pixel precision.
