### ISSUE TITLE
Best way to change waveform sensitivity?

### ISSUE THREAD

**Issue by AquaCobell** [phandasm/waveform#39]
I don't know to much about music especially the technical part, whats the best way to change the sensitivity? I saw the normalize Volume option but its sometimes a little bit too sensitive.

**Comment by phandasm** [comment]
The "Floor" and "Ceiling" options act as a sort of "zoom".
Raising the ceiling and lowering the floor will keep the graph in visible range over a larger volume range, and conversely bringing them closer together will "zoom in" on a specific volume range.
Lowering them both will make everything appear louder.

Basically you want to match the floor and ceiling to the volume range of the audio source.
The volume normalization option is meant to help with cases where said range is inconsistent.

**Comment by AquaCobell** [comment]
very helpful, thank you
