### ISSUE TITLE
Prebuilt binaries for linux

### ISSUE THREAD

**Issue by yavko** [phandasm/waveform#4]
Im using the flatpak version of obs and cant install libobs, so it would be nice if you could provide binaries or setup gh actions!

**Comment by phandasm** [comment]
I do plan to do something about linux binaries, next release should include them.
Source build is preferred because some distros (notably Ubuntu 20.04) ship with an obs version that is too old and support for one of the newer APIs is toggled via cmake.

**Comment by phandasm** [comment]
Linux binaries now published automatically as of [v1.1.0-rc1](https://github.com/phandasm/waveform/releases/tag/v1.1.0-rc1)

**Comment by yavko** [comment]
> Linux binaries now published automatically as of [v1.1.0-rc1](https://github.com/phandasm/waveform/releases/tag/v1.1.0-rc1)

Thanks ill take a look at this tomorrow!
