### ISSUE TITLE
how to i make this

### ISSUE THREAD

**Issue by aaskjer** [phandasm/waveform#40]
How do i make these?

updated from 1.0.0 to 1.5.0 but i cannot do [that](https://duke.nuked.earth/u/​‌​‌​​‌​​‌​​‌‌​​​​‌‌​‌‌​​‌‌‌​‌‌‌​‌​‌​​​‌​‌​‌‌​​‌​‌​​​‌​‌​‌​​‌​​​)

**Comment by phandasm** [comment]
You should see the new display types in the "Display Mode" dropdown as well as the "Radial Layout" checkbox in the settings.
If they're not there, then the update may not have been installed properly.

If you're on Windows, make sure you're using 64-bit OBS. Waveform 1.5 dropped 32-bit support as did OBS 28.
Also note that the original 1.0 version had some issues so sources made with that version won't work anymore.

It might be best to completely uninstall and reinstall waveform if you're coming from a version that old.

**Comment by aaskjer** [comment]
issue was i installed OBS on another SSD. waveform don't ask for a patch so it installed it on C which obviously is not where my obs is installed. copied the files and everything works. thx aynways.

**Comment by aaskjer** [comment]
issue was i installed OBS on another SSD. waveform don't ask for a patch so it installed it on C which obviously is not where my obs is installed. copied the files and everything works. thx aynways.
