### ISSUE TITLE
[Feature Request] Pulse/intensity mode

### ISSUE THREAD

**Issue by z0w13** [phandasm/waveform#47]
Basically the louder the audio, the brighter the color from black to white, configurable, or otherwise. Mainly useful for enabling other effects based on keying, etc. 

Could also alternatively do RGB for low/mid/high frequencies to get even more possibilities based on frequency buckets

**Comment by phandasm** [comment]
Sounds interesting, I'll see what I can do.

**Comment by phandasm** [comment]
Added in 1.7.0
