### ISSUE TITLE
question

### ISSUE THREAD

**Issue by WuglyakBolgoink** [phandasm/waveform#5]
Is it compatible to macOS?

**Comment by phandasm** [comment]
Theoretically it should compile for x86 based macs.
Unfortunately I don't have a mac and have never tried it so I can't make any guarantees there.

**Comment by aptonline** [comment]
I second a guide for building on Mac, I'm happy to provide any testing to get this supported.

**Comment by phandasm** [comment]
Unfortunately I don't know the exact build steps for mac.
Currently it will not build for the newer macs with ARM CPUs due to the extensive use of AVX, and unless FFTW is available from homebrew the cmake script will need to be tweaked to get FFTW built properly with GCC/Clang.

I'll see if i can get ahold of a mac somehow.
This is not the first time this has been an issue so it'd be nice to just have one on hand at this point.

**Comment by phandasm** [comment]
So i've pushed an updated CMakeLists to the `develop` branch.
I *think* it should build on mac provided you can get libobs built.

Build instructions should resemble the linux instructions except you'll need to build obs separately and point CMake to it with
 `-DLibObs_ROOT="path/to/obs-studio"`
CMake will attempt to use the system (homebrew) provided FFTW, if that doesn't work you can build it from source by passing
`-DBUILTIN_FFTW=ON`.
Build instructions for OBS: https://obsproject.com/wiki/build-instructions-for-mac

I tested BUILTIN_FFTW=ON with both GCC and Clang on linux, I'll have to see if I can get CI to do a mac build later

**Comment by aptonline** [comment]
Any news on CI doing a Mac build?

**Comment by phandasm** [comment]
So I still can't test it and I'm sot sure I got the plugin folder structure right for mac but it builds: https://github.com/phandasm/waveform/releases/tag/v1.3.0-beta1

Minimum OS is ostensibly 10.13 (x86_64 CPUs only)

**Comment by aptonline** [comment]
I’ll give it a test and let you know. Thanks.

**Comment by aptonline** [comment]
Pleased to report that it installs and seems to work perfectly on my Mac running Catalina (10.15.7). I’ll do some further testing and let you know on my main machine which is running Mojave (10.14).

Thanks again.

**Comment by phandasm** [comment]
Good to know, thanks for testing it 👍
