### ISSUE TITLE
All the the songs I've tried doesn't generate bars at the top for the Radial Layout.

### ISSUE THREAD

**Issue by Bj007pro** [phandasm/waveform#52]
I've played around with the options trying different things, but with what I have tried, at top of the circle the bars are small and makes it look horrible.

![image](https://github.com/phandasm/waveform/assets/24400879/fc4bd8b2-0530-4128-b9e2-3a3d764cbd4e)

Is there an option I haven't tried or seen, or is it something else?

Thanks.

**Comment by phandasm** [comment]
There's probably just not much going on in the upper frequencies (I assume this is mirrored?).
There's a few reasons why that might be the case but the solution is to reduce the "High Cutoff" so that those frequencies aren't included in the graph.

**Comment by Bj007pro** [comment]
> There's probably just not much going on in the upper frequencies (I assume this is mirrored?). 

Yes, this is mirrored.

>There's a few reasons why that might be the case but the solution is to reduce the "High Cutoff" so that those frequencies aren't included in the graph.

Thank you! This help!
