### ISSUE TITLE
Unable to use on Ubuntu

### ISSUE THREAD

**Issue by nfoert** [phandasm/waveform#54]
I'm running **OBS Studio 29.1.3** installed from **Flatpak** on **Ubuntu 22.04.3 LTS**. I've tried building the plugin from source, and installing from the .deb. No matter what I do, the Waveform Visualizer does not show up in the sources list. 
Is Waveform currently not supported on the latest version of OBS?

If I remember correctly, I was able to get the plugin to work on the Snap version of OBS, but I need to use the Flatpak version for some of my other plugins to function.

Is there anything obvious that I'm missing?

**Comment by phandasm** [comment]
If you're using OBS from flatpak then you need to install waveform through flatpak as well.
`flatpak install flathub com.obsproject.Studio.Plugin.waveform`

**Comment by nfoert** [comment]
Worked perfectly, thanks @phandasm. I'm going to make a PR to add this to the README, because that difference wasn't clear to me, and I expect other users may need to know this as well.

Thanks again!
