### ISSUE TITLE
Request for sin^4 window + upto 65536 Samples

### ISSUE THREAD

**Issue by Sam-Belliveau** [phandasm/waveform#58]
My goal is to replicate the graph shown in the following video: https://youtu.be/cIQ9IXSUzuM?si=t4-2h-clXiYK6o0A&t=775 

<img width="800" alt="image" src="https://github.com/phandasm/waveform/assets/28713194/7524f0ae-f451-4129-9373-1f07f8a96fdb">

# Why sin^4

Typically, many window functions, such as Hann, are a "Raised Cosine" functions. Which look like:
<img width="800" alt="image" src="https://github.com/phandasm/waveform/assets/28713194/d5525ea9-6a6e-4c9d-a9b2-119d8962b558">

This is actually just equal to sin^2. On the other hand, sin^4 has the advantage of tapering more on the sides, which looks like:
<img width="800" alt="image" src="https://github.com/phandasm/waveform/assets/28713194/28867813-0a86-486d-8b70-853071617090">

When combined with a large sample window like 65536 samples, this could reduce the noise in the graph, leading to better graphs, and reduce the noise. This would also make the graph less jittery from frame to frame. As you can see from the youtube video, their graph is very smooth, and they are using the same FFT library that this project is. 

# Replace Exponential Moving Average with time variant version.

The moving average lets you select "gravity," which I assume is just the amount you weight the previous value with the new one. This is in general not a great way to do this because it depends on frame rate. What you should do is replace this with this equation that is calculated on each frame:

<img width="200" alt="image" src="https://github.com/phandasm/waveform/assets/28713194/85d612ce-a236-4d5b-a8be-81f74d17faae">

In code this would be `gravity = std::exp(-dt / m_RC)`. Where dt is the time in seconds between the previous frame and this one. RC can be changed such that higher RC values make the graph smoother and lower RC values make the graph update faster. This would be easier to control than the Gravity knob, while leading to the same smoothing effect.

I would be willing to make a PR that does these if this is too much of a hassle, I was just wondering if these would be easy to implement?

**Comment by Sam-Belliveau** [comment]
# Frequency Response of Various Windows: [Desmos Used in Test](https://www.desmos.com/calculator/zkb49o2dc7)

What you will noice is that the different window functions have tradeoffs between the width of the frequency response and the noise floor. I personally prefer a lower noise floor as you can always shrink the frequency response width by increasing the number of samples. (I show this in the last image)

## no window
<img width="500" alt="image" src="https://github.com/phandasm/waveform/assets/28713194/68c12794-3a87-45ea-aba5-ffefca3c2c5c">

## Blackman Harris
<img width="500" alt="image" src="https://github.com/phandasm/waveform/assets/28713194/9d815c28-b579-4d11-b846-dead056b8c79">


## sin^1
<img width="500" alt="image" src="https://github.com/phandasm/waveform/assets/28713194/7be66487-554b-4517-919e-06f8a4003c9a">

## sin^2 (Hann)
<img width="500" alt="image" src="https://github.com/phandasm/waveform/assets/28713194/ae58370f-02d7-4619-ae7f-aca7402bfb99">

## sin^4
<img width="500" alt="image" src="https://github.com/phandasm/waveform/assets/28713194/032fea4c-8619-41cd-8de3-1074967a52cc">

## sin^6
<img width="500" alt="image" src="https://github.com/phandasm/waveform/assets/28713194/55d94205-c4f1-461b-8af1-e67118dc95e1">

## sin^8
<img width="500" alt="image" src="https://github.com/phandasm/waveform/assets/28713194/0179058e-8679-4690-879b-4cb14db5dcdf">

## sin^10
<img width="500" alt="image" src="https://github.com/phandasm/waveform/assets/28713194/bdf0e52d-b020-4cf2-941f-14987d512444">

## sin^10 (2x number of samples)

<img width="500" alt="image" src="https://github.com/phandasm/waveform/assets/28713194/4b72b07e-658e-4a8b-8f91-09c1a517780d">

**Comment by phandasm** [comment]
Sure, the sin^4 window is no problem.
And I had actually considered replacing the EMA with a time compensated version previously but I don't want to break people's settings so that one would be an addition rather than a replacement.

**Comment by Sam-Belliveau** [comment]
It might be worth adding a sin^10 or sin^16 option that could be combined with 65k samples. That would be for when you want frequency accuracy more than anything else as those windows at that sample size would have a practically zero noise floor. It would be less useful for real time audio though because of the ~0.5s latency it would add. Maybe a warning at high FFT sizes saying something like, "high sample sizes add latency to measurements".

**Comment by phandasm** [comment]
All pushed to master now.
Scaling on the EMA slider probably leaves something to be desired but it at least works for the moment.
Let me know if there's any issues.
