### ISSUE TITLE
Plugin Crashes with OBS 29.1.3

### ISSUE THREAD

**Issue by 3345meggs** [phandasm/waveform#59]
By adding the plugin in a scene in OBS and config an audio Source, OBS crashes.

**Comment by phandasm** [comment]
What platform?
Seems to work fine with OBS 29.1.3 on windows.
Crash log would be helpful.

**Comment by 3345meggs** [comment]
Hi, sorry it was too late :) Platform Windows 11. Crash log attached.
[Crash 2023-11-12 14-13-18.txt](https://github.com/phandasm/waveform/files/13328074/Crash.2023-11-12.14-13-18.txt)

**Comment by phandasm** [comment]
Huh, that seems like a channel mapping or audio format issue but I can't reproduce it.
Are you using waveform 1.7?

**Comment by 3345meggs** [comment]
Yes, latest version

**Comment by 3345meggs** [comment]
What Audio Format or Source is default for Waveform?
We have tested something and have choosen Output Bus, OBS don't crash but we don't see anything from the plugin.

**Comment by phandasm** [comment]
Internally waveform expects planar float audio.
Usually OBS handles the conversion so it *shouldn't* matter what the source is using, but issues can arise from ABI incompatibilities with forks of OBS (e.g. Music Edition) or misbehaving plugins (VLC's bogus timestamps).

I did actually test the VBAN plugin and it seemed to work just fine, but I had it mapped to standard stereo so maybe it depends on what channels are in use.

The audio callback unfortunately doesn't give much info on the provided audio beyond frame count.

> We have tested something and have choosen Output Bus, OBS don't crash but we don't see anything from the plugin.

If your channel mapping is nonstandard, try setting `Channel Mode` to `Single` and cycle through channels until you see something.

**Comment by 3345meggs** [comment]
Hi, after a while today i tried again and it works. I have updated to OBS 30.0.2 and to latest Waveform plugin.
