### ISSUE TITLE
plugin just doesn't show up in obs

### ISSUE THREAD

**Issue by reissecup** [phandasm/waveform#62]
the plugin doesn't show up in obs on my linux manjaro pc or on my windows laptop.

**Comment by phandasm** [comment]
Tested with OBS 30 on Win 11 and Fedora 38 without issue, make sure you installed correctly.

**Comment by reissecup** [comment]
it turned out on windows i just had to update obs, but for manjaro i reinstalled and it still isn't showing up

**Comment by phandasm** [comment]
Are you getting OBS from the package manager or from flatpak?
If you're using flatpak then you need to install waveform from flatpak as well.
If you're using the package manager then you might need to figure out where OBS looks for its plugins on your distro and make sure waveform is actually installed there.

By default `make install` puts waveform in `~/.config/obs-studio/plugins` for source build, which should be correct for most distros, *but only for the user running the install command.*

**Comment by reissecup** [comment]
found out that i had to install it with yay

**Comment by phandasm** [comment]
Glad you got it sorted out
