### ISSUE TITLE
Compiling for Linux aarch64

### ISSUE THREAD

**Issue by a-plastic-bag** [phandasm/waveform#74]
I'm trying to build this on a aarch64 Fedora 40 according to the build instructions, but upon running `make` I get the following error:
```
[ 80%] Building CXX object CMakeFiles/waveform.dir/src/source.cpp.o
In file included from /home/user/waveform/src/source.cpp:34:
/home/user/waveform/deps/cpu_features/include/cpuinfo_x86.h:292:2: error: #error "Including cpuinfo_x86.h from a non-x86 target."
  292 | #error "Including cpuinfo_x86.h from a non-x86 target."
```
...and then further down:
```
make[2]: *** [CMakeFiles/waveform.dir/build.make:90: CMakeFiles/waveform.dir/src/source.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:103: CMakeFiles/waveform.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```
I'm not sure where to go from here, whether it's just a flag I'm not setting or that the software cannot be built on aarch64 Linux. If that's the case, how difficult would it be to make it compatible?

**Comment by phandasm** [comment]
You'll need to add `-DDISABLE_X86_SIMD=ON` to your CMake options

**Comment by a-plastic-bag** [comment]
> You'll need to add `-DDISABLE_X86_SIMD=ON` to your CMake options

Thanks so much, that did the trick!

**Comment by a-plastic-bag** [comment]
Also, it might be a good idea to add this to the build instructions in case others want to build for aarch64 Linux as well.
