### ISSUE TITLE
Visualize Specific Frequency (Pitch Detection)

### ISSUE THREAD

**Issue by navidrasi** [phandasm/waveform#75]
Thank you for awesome plugin this is great , i would like to create some effect when specific frequency played ex 174 hz , for now i made it work by selecting the range between 173 and 174 but it is not as accurate as i need it, i have raised the FFT to the max which makes it very accurate just need to be able to select one frequency  but  when i set the low cut off and high cut off on same number it start showing other frequencies too

range 
![range](https://github.com/user-attachments/assets/36bd1d4c-bac0-40cb-ade0-adf16a328120)

specific frequency 
![specific](https://github.com/user-attachments/assets/ed73263c-663a-438d-ab52-97d551c5f51b)

thanks again

**Comment by phandasm** [comment]
Yeah that's supposed to work, I just made a typo.
Already pushed a fix if you're able to build from source.

**Comment by navidrasi** [comment]
thank you very much , that did the trick , cheers
