### ISSUE TITLE
Is there a way to expand the waveform box?

### ISSUE THREAD

**Issue by Mapsking** [phandasm/waveform#76]
I am relatively new to OBS, so maybe this is on me. However, when I experiment with the floor and ceiling sliders, the waveform gets cut off. Is there a way to increase the size of the box? increasing the bounding box in OBS seems to do nothing. Changing the video height only seems to stretch it vertically, and leave the cutoff. If it is hardcoded, would you consider adding a way to change it, and if not, do you have any suggestions on how to achieve it? 

Maybe I am doing it wrong, but the visualizer seems to be taller/shorter depending on the dB. I play a lot of music rhythm games, so I'd like the visualizer to be at a consistent height. I noticed when playing softer and quieter songs that the visualizer was barely visible, and when playing at a higher dB (?, at least higher music volume in game), it was much taller, and cutoff. 

Here are a couple pictures for reference. These pictures are zoomed in, but hopefully they help demonstrate. The cutoff on the left side mostly. 

![image](https://github.com/user-attachments/assets/e6e9be82-c4bd-4cf3-865c-7eaa4e64243f)
![image](https://github.com/user-attachments/assets/bdcaad0d-73cd-44f5-a3a9-eb11e4005523)

This following image is at 10% in-game volume.
![image](https://github.com/user-attachments/assets/91a419dd-19cb-40f3-b203-1e12cbd7a089)

This following image is at 100% in game volume.
![image](https://github.com/user-attachments/assets/c838d7d9-3829-4f25-a17b-0372de269833)

**Comment by phandasm** [comment]
Did you lower the 'Ceiling' option? Because that will result in the top getting cut off at full volume.
Make sure you didn't crop it in OBS either.

If you want the graph to be the same height regardless of volume then turn on volume normalization.

**Comment by Mapsking** [comment]
Oh, I didn't know that. Yes, I did modify the ceiling. Is normalization going to create a lot of extra strain on resources?

**Comment by phandasm** [comment]
It'll use slightly more resources but shouldn't make a noticeable difference.

**Comment by Mapsking** [comment]
OK, thanks for the info, and all your work on this, it's amazing!

**Comment by Mapsking** [comment]
Actually, I looked, and was mistaken, it must have been an earlier test. Now, the ceiling is at it's default setting of 0, normalized volume on, and technically, the bars are not going beyond it, but a filter adding a glow is. 
![image](https://github.com/user-attachments/assets/07760b77-ca08-40ba-a22b-59862b04d9b3)
Also, it is not cropped in OBS
![image](https://github.com/user-attachments/assets/8927d424-f9e8-430c-9401-3240b8d48b01)
![image](https://github.com/user-attachments/assets/adceb909-d65f-4111-b434-526bc2c016dc)
You can see a few spots where it is still getting cut off. Is there any other way to prevent this, other than turning off the filters?

**Comment by phandasm** [comment]
Make the source taller ('Height' option in settings), turn on volume normalization and drop the normalization target until you have enough headroom.

Not sure why your bounding box looks like that though, might want to reset any transform you have on it first (right click->transform->reset transform).

**Comment by Mapsking** [comment]
With some tweaking, I was able to modify it and remake it to prevent this. Thanks.
