### ISSUE TITLE
Packaging for Flatpak

### ISSUE THREAD

**Issue by rmnvgr** [phandasm/waveform#8]
Hello,

Thank you for your useful plugin.

As you may know, OBS is [officially released on Linux as a Flatpak](https://obsproject.com/download#linux), which is a distro-agnostic software delivery mechanism, and published on Flathub, the main Flatpak repository.

It's possible to also package OBS plugins as Flatpaks and publish them on Flathub. The advantage is that users have a central place to install OBS and plugins, and keep everything up to date. [As you can see here](https://github.com/flathub/com.obsproject.Studio/wiki/Plugins), plugins are presented in application installers alongside OBS.

If that sounds interesting to you, I can write a Flatpak manifest for Waveform, submit it to Flathub, and maintain it.

I already got something working, but I faced some issues:

- Building with gcc failed completely ([build logs](https://github.com/phandasm/waveform/files/8661702/build.log))

- Building with clang also failed until I added a missing include of `stdint.h` in `math_funcs.hpp`
- The directory structure is different for packaged OBS plugins (not specific to Flatpak):
  - `$PREFIX/lib/obs-plugins/libwaveform.so`
  - `$PREFIX/share/obs/obs-plugins/waveform/gradient.effect`
  - `$PREFIX/share/obs/obs-plugins/waveform/locale/en-US.ini`

I used the following patches to get Waveform to build and installed at the correct place:

<details>

<summary><code>waveform.patch</code></summary>

```patch
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 0c50aca..1095ca2 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -145,8 +145,8 @@ else()
     if(APPLE)
         install(TARGETS waveform DESTINATION "waveform/bin")
     else()
-        install(TARGETS waveform DESTINATION "waveform/bin/$<IF:$<EQUAL:${CMAKE_SIZEOF_VOID_P},8>,64bit,32bit>")
+        install(TARGETS waveform DESTINATION "lib/obs-plugins")
     endif()
-    install(FILES "data/gradient.effect" DESTINATION "waveform/data/")
-    install(FILES "data/locale/en-US.ini" DESTINATION "waveform/data/locale")
+    install(FILES "data/gradient.effect" DESTINATION "share/obs/obs-plugins/waveform")
+    install(FILES "data/locale/en-US.ini" DESTINATION "share/obs/obs-plugins/waveform/locale")
 endif()
diff --git a/src/math_funcs.hpp b/src/math_funcs.hpp
index b8e0ab4..9bc0307 100644
--- a/src/math_funcs.hpp
+++ b/src/math_funcs.hpp
@@ -19,6 +19,7 @@
 #include <cmath>
 #include <algorithm>
 #include <type_traits>
+#include <stdint.h>
 
 template<typename T>
 std::enable_if_t<std::is_floating_point_v<T>, T> log_interp(T a, T b, T t)
```

</details>

Flathub also requires [AppStream metadata](https://www.freedesktop.org/software/appstream/docs/). This is not Flatpak-specific and is used by software installers, so you may want to have it upstream for other packagers. I wrote these ones:

<details>

<summary><code>com.obsproject.Studio.Plugin.waveform.metainfo.xml</code></summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<component type="addon">
	<id>com.obsproject.Studio.Plugin.waveform</id>
	<extends>com.obsproject.Studio</extends>
	<name>Waveform</name>
	<summary>Audio spectral analysis plugin for OBS</summary>
	<url type="homepage">https://github.com/phandasm/waveform</url>
	<url type="bugtracker">https://github.com/phandasm/waveform/issues</url>
	<metadata_license>CC0-1.0</metadata_license>
	<project_license>GPL-3.0</project_license>
</component>
```

</details>

Let me know what you think of this.

**Comment by phandasm** [comment]
Hi!
I wouldn't mind publishing to flathub, but it might be better if I maintained it, if only for the sake of keeping things centralized.

I do appreciate the patch and metadata file, I'll see about getting a flatpak build set up. Really not sure why GCC is having a fit about the intrinsic headers.

**Comment by phandasm** [comment]
> The patch is rather crude, as it simply replaces the paths. It might be better to add an option for package paths, but I'm not familiar with CMake.

Yeah, the patch should no longer be necessary. I've added a CMake option so `-DPACKAGED_INSTALL=ON` will switch to the appropriate folder structure.
The missing include and metainfo file have also been added, so I think that should be it?

I went ahead and created the `v1.3.0-flatpak` tag for these changes so if everything's good and you'd like to submit it, feel free to do so.

**Comment by rmnvgr** [comment]
Thank you! It works without any patches now. I had to disable the automatic PR creation for now, because the tool thinks that `v1.3.0` comes after `v1.3.0-flatpak` and will want to update to that version. I'll re-enable it on the next proper tag.

I've opened https://github.com/flathub/flathub/pull/3136 so you can keep track of the submission.

**Comment by phandasm** [comment]
Oops, didn't realize the tag would be an issue. I just didn't want to version bump since nothing changed in the plugin itself.
Very nice though 👍

**Comment by rmnvgr** [comment]
The submission has been accepted, and you should have been invited to [the repository](https://github.com/flathub/com.obsproject.Studio.Plugin.waveform)!

> Oops, didn't realize the tag would be an issue. I just didn't want to version bump since nothing changed in the plugin itself.

No worries!

**Comment by phandasm** [comment]
Nice!
I tested the flatpak build and everything seems good so I'll go ahead and close this.

**Comment by rmnvgr** [comment]
By the way, if you want to have some statistics for the number of installations, they are available here: https://klausenbusk.github.io/flathub-stats/#ref=com.obsproject.Studio.Plugin.waveform/stable&interval=infinity&downloadType=installs

**Comment by phandasm** [comment]
Good to know, thanks 👍
